src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Outdoor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Clothing</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemImageTriggerTest.cls
@isTest
public class ItemImageTriggerTest {
	@isTest
	static void testTriggerWithMock() {
		Test.setMock(HttpCalloutMock.class, new UnsplashServiceTest.MockHttpResponse());

		Test.startTest();
		Item__c item = new Item__c(
				Name = 'Test Camera',
				Type__c = 'Electronics',
				Family__c = 'Home'
		);
		insert item;
		Test.stopTest();

		Item__c updatedItem = [SELECT Image__c FROM Item__c WHERE Id = :item.Id];
		System.assertEquals('https://test.com/image.jpg', updatedItem.Image__c);
	}
}