src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase__c.object
<CustomObject>
    <description>Stores purchase information</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItems__c</fullName>
        <label>Total Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <description>Line items for purchases</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>Item Id</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase Id</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Line</label>
    <nameField>
        <label>Purchase Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseLineTriggerTest.cls
@isTest
public class PurchaseLineTriggerTest {
	@testSetup
	static void setup() {
		Account acc = new Account(Name='Test Account');
		insert acc;

		Item__c item = new Item__c(Name='Laptop', Price__c=1000);
		insert item;

		Purchase__c purchase = new Purchase__c(ClientId__c=acc.Id);
		insert purchase;
	}

	@isTest
	static void testTriggerUpdatesPurchaseTotals() {
		Item__c item = [SELECT Id, Price__c FROM Item__c LIMIT 1];
		Purchase__c purchase = [SELECT Id FROM Purchase__c LIMIT 1];

		Test.startTest();
		PurchaseLine__c line = new PurchaseLine__c(
				PurchaseId__c = purchase.Id,
				ItemId__c = item.Id,
				Amount__c = 2,
				UnitCost__c = item.Price__c
		);
		insert line;
		Test.stopTest();

		Purchase__c updatedPurchase = [SELECT TotalItems__c, GrandTotal__c FROM Purchase__c WHERE Id = :purchase.Id];
		System.assertEquals(2, updatedPurchase.TotalItems__c, '2 items required');
		System.assertEquals(2000, updatedPurchase.GrandTotal__c, 'grand total must be 2000');
	}
}