src/objects/Purchase__c.object
<CustomObject>
    <description>Stores purchase information</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <description>Line items for purchases</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>Item Id</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase Id</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Line</label>
    <nameField>
        <label>Purchase Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseController.cls
public with sharing class PurchaseController {
	@AuraEnabled
	public static Id createPurchaseWithLines(Id clientId, List<PurchaseLineWrapper> lines) {
		if (clientId == null) {
			throw new AuraHandledException('Client ID cannot be null');
		}
		if (lines == null) {
			lines = new List<PurchaseLineWrapper>();
		}
		for (PurchaseLineWrapper line : lines) {
			if (line.amount < 0) {
				throw new AuraHandledException('Amount cannot be negative');
			}
			if (line.unitCost < 0) {
				throw new AuraHandledException('Unit cost cannot be negative');
			}
		}

		Purchase__c purchase = new Purchase__c(ClientId__c = clientId);
		insert purchase;

		List<PurchaseLine__c> purchaseLines = new List<PurchaseLine__c>();
		for (PurchaseLineWrapper line : lines) {
			purchaseLines.add(new PurchaseLine__c(
					PurchaseId__c = purchase.Id,
					ItemId__c = line.itemId,
					Amount__c = line.amount,
					UnitCost__c = line.unitCost
			));
		}
		insert purchaseLines;

		return purchase.Id;
	}

	public class PurchaseLineWrapper {
		@AuraEnabled public Id itemId {get; set;}
		@AuraEnabled public Integer amount {get; set;}
		@AuraEnabled public Decimal unitCost {get; set;}
	}
}